server:
  port: 7001
spring:
  application:
    name: mservice-authen
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    registerWithEureka: true  #默认就是true，是否在注册中心注册
    fetchRegistry: false
logging:
  level:
    com.netflix.discovery: 'INFO'
    org.springframework.cloud: 'INFO'